server:
  port: 16070
spring:
  application:
    name: langchain4j-springboot

# 向量存储配置
embedding:
  store:
    type: memory  # 可选: memory(内存) 或 redis(需要RediSearch模块)

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${API_KEY_DASH_SCOPE}
        model-name: qwen-max
        temperature: 0.7
      streaming-chat-model:
        api-key: ${API_KEY_DASH_SCOPE}
        model-name: qwen-max
        temperature: 0.7
      embeddingModel:
        api-key: ${API_KEY_DASH_SCOPE}
        model-name: text-embedding-v2

gaode:
  baseUrl: https://restapi.amap.com/v3/weather/weatherInfo
  api-key: ${API_KEY_GAODE}

redis:
  host: localhost
  port: 6379
  #如果开启了认证，需要设置用户名和密码，用户名如未设置则使用default
#  username: default
#  password: 123456

# searxng。国内搜索引擎支持较差。用它的主要原因是免费。文档https://docs.searxng.org/
searxng:
  base-url: http://localhost:19112/
  engines: 360search  # 搜索引擎，逗号隔开

logging:
  level:
    dev:
      langchain4j: debug
      ai4j: debug
